# Top-level application configuration.
app:
  # The port on which the application server will listen.
  port: "8080"
  # The host address for the application server.
  host: "0.0.0.0"
  # List of trusted origins for CORS and other security policies.
  trustedOrigins:
    - "https://app.example.com"
    - "https://api.example.com"
  # The external domain name for the application. Used for generating external URLs.
  externalDomain: "app.example.com"
  # A boolean to indicate if the external domain uses HTTPS.
  externalSecure: true
  # OpenAPIPath is the path to the OpenAPI spec without extension. If set
  # to `/openapi` it will allow clients to get `/openapi.json` or
  # `/openapi.yaml`, for example.
  openAPIPath: "/openapi"

# Auth service configuration.
auth:
  url: "https://auth.example.com"

# PostgREST service configuration.
pgrest:
  url: "https://postgrest.example.com"

# Database connection configuration.
database:
  # The full connection URL for the database (e.g., PostgreSQL, MySQL).
  url: "postgres://user:password@db.example.com:5432/my-app-db?sslmode=disable"

s3:
  # The endpoint URL for the S3-compatible storage service.
  endpoint: "s3.example.com"
  # Enable SSL for secure connections
  useSSL: true
  # The access key ID for S3 authentication
  accessKeyID: "your-access-key"
  # The secret access key for S3 authentication
  secretAccessKey: "your-secret-key"
  # The region where the S3 bucket is located.
  region: "tw-1"

# Kubernetes-specific configuration.
kube:
  # Path to the Kubernetes configuration file. Leave empty to use in-cluster config.
  configPath: ""
  # Project-specific Kubernetes settings.
  project:
    # The Kubernetes namespace where the application is running.
    namespace: "default"
    # The name of the Kubernetes secret containing TLS certificates.
    tlsSecretName: "app-tls-secret"

logging:
  # Log level for the application (e.g., debug, info, warn, error).
  level: "info"
